import jsPDF from 'jspdf';

export async function generatePDF(content, filename = 'document.pdf') {
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  pdf.setFont('helvetica');
  
  pdf.setFontSize(20);
  pdf.setTextColor(26, 58, 92);
  pdf.text('ARK Genie - AI Insurance Assistant', 105, 20, { align: 'center' });
  
  pdf.setDrawColor(212, 175, 55);
  pdf.setLineWidth(0.5);
  pdf.line(20, 25, 190, 25);
  
  pdf.setFontSize(11);
  pdf.setTextColor(45, 52, 54);
  
  const plainText = content
    .replace(/#{1,6}\s/g, '')
    .replace(/\*\*/g, '')
    .replace(/\*/g, '')
    .replace(/`/g, '')
    .replace(/-\s/g, '• ');
  
  const lines = pdf.splitTextToSize(plainText, 170);
  let yPosition = 35;
  
  lines.forEach((line) => {
    if (yPosition > 280) {
      pdf.addPage();
      yPosition = 20;
    }
    pdf.text(line, 20, yPosition);
    yPosition += 6;
  });
  
  const pageCount = pdf.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i);
    pdf.setFontSize(9);
    pdf.setTextColor(150);
    pdf.text(
      `ARK Genie | Page ${i} / ${pageCount}`,
      105,
      290,
      { align: 'center' }
    );
  }
  
  pdf.save(filename);
  
  return true;
}

export async function generateAnalysisReport(analysisData, customerName = 'Customer') {
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  pdf.setFillColor(26, 58, 92);
  pdf.rect(0, 0, 210, 40, 'F');
  
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(22);
  pdf.text('Insurance Analysis Report', 105, 20, { align: 'center' });
  
  pdf.setFontSize(12);
  pdf.text(`${customerName} - ${new Date().toLocaleDateString('ko-KR')}`, 105, 32, { align: 'center' });
  
  pdf.setTextColor(45, 52, 54);
  pdf.setFontSize(11);
  
  const lines = pdf.splitTextToSize(analysisData, 170);
  let yPosition = 50;
  
  lines.forEach((line) => {
    if (yPosition > 280) {
      pdf.addPage();
      yPosition = 20;
    }
    pdf.text(line, 20, yPosition);
    yPosition += 6;
  });
  
  pdf.setFontSize(9);
  pdf.setTextColor(150);
  pdf.text('Generated by ARK Genie - AI Insurance Assistant', 105, 290, { align: 'center' });
  
  pdf.save(`analysis_report_${Date.now()}.pdf`);
  
  return true;
}

export async function generateProposalPDF(proposalContent, customerName = 'Customer') {
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  pdf.setFillColor(26, 58, 92);
  pdf.rect(0, 0, 210, 45, 'F');
  
  pdf.setFillColor(212, 175, 55);
  pdf.rect(0, 45, 210, 3, 'F');
  
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(24);
  pdf.text('Insurance Proposal', 105, 22, { align: 'center' });
  
  pdf.setFontSize(14);
  pdf.text(`For ${customerName}`, 105, 35, { align: 'center' });
  
  pdf.setTextColor(45, 52, 54);
  pdf.setFontSize(11);
  
  const plainText = proposalContent
    .replace(/#{1,6}\s/g, '')
    .replace(/\*\*/g, '')
    .replace(/\*/g, '')
    .replace(/-\s/g, '• ');
  
  const lines = pdf.splitTextToSize(plainText, 170);
  let yPosition = 58;
  
  lines.forEach((line) => {
    if (yPosition > 275) {
      pdf.addPage();
      yPosition = 20;
    }
    pdf.text(line, 20, yPosition);
    yPosition += 6;
  });
  
  pdf.save(`proposal_${customerName}_${Date.now()}.pdf`);
  
  return true;
}
